# Generated by Django 5.0.4 on 2024-04-17 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Description')),
                ('balance', models.FloatField(verbose_name='Balance')),
                ('show_card', models.BooleanField(verbose_name='Show Card')),
                ('show_pie', models.BooleanField(verbose_name='Show Pie Chart')),
                ('show_line', models.BooleanField(verbose_name='Show in Line Chart')),
                ('theme_color_hash', models.CharField(max_length=7, verbose_name='Theme Color')),
                ('theme_icon_fa_class', models.CharField(max_length=50, verbose_name='Theme Icon FA class')),
                ('account_type', models.CharField(choices=[('SVG', 'Savings'), ('CHK', 'Checking'), ('INV', 'Investment')], default='CHK', max_length=3)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Description')),
                ('theme_color_hash', models.CharField(max_length=7, verbose_name='Theme Color')),
                ('category_type', models.CharField(choices=[('INC', 'Income'), ('EXP', 'Expense'), ('TRN', 'Transfer')], default='EXP', max_length=3)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('note', models.TextField(verbose_name='Note')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_management_api.account', verbose_name='Account')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_management_api.category', verbose_name='Category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
