# Generated by Django 5.0.4 on 2024-04-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
