# Generated by Django 5.0.4 on 2024-04-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_api', '0003_alter_account_theme_icon_fa_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='show_card',
            field=models.BooleanField(default=False, verbose_name='Show Card'),
        ),
        migrations.AlterField(
            model_name='account',
            name='show_line',
            field=models.BooleanField(default=False, verbose_name='Show in Line Chart'),
        ),
        migrations.AlterField(
            model_name='account',
            name='show_pie',
            field=models.BooleanField(default=False, verbose_name='Show Pie Chart'),
        ),
        migrations.AlterField(
            model_name='account',
            name='theme_color_hash',
            field=models.CharField(max_length=7, null=True, verbose_name='Theme Color'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='theme_color_hash',
            field=models.CharField(max_length=7, null=True, verbose_name='Theme Color'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(null=True, verbose_name='Note'),
        ),
    ]
