# Generated by Django 5.0.7 on 2024-09-23 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_api', '0008_alter_account_user_id_alter_category_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trn_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('INV', 'Investment'), ('SVG', 'Savings'), ('CHK', 'Checking')], default='CHK', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('TRN', 'Transfer'), ('EXP', 'Expense'), ('INC', 'Income')], default='EXP', max_length=3),
        ),
    ]
