# Generated by Django 5.0.7 on 2024-09-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_api', '0010_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CHK', 'Checking'), ('SVG', 'Savings'), ('INV', 'Investment')], default='CHK', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('INC', 'Income'), ('EXP', 'Expense'), ('TRN', 'Transfer')], default='EXP', max_length=3),
        ),
    ]
