# Generated by Django 5.0.7 on 2024-11-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_api', '0012_remove_account_balance_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CHK', 'Checking'), ('INV', 'Investment'), ('SVG', 'Savings')], default='CHK', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('EXP', 'Expense'), ('TRN', 'Transfer'), ('INC', 'Income')], default='EXP', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account_management_api.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account_management_api.category', verbose_name='Category'),
        ),
    ]
