# Generated by Django 5.1.3 on 2025-02-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_api', '0020_alter_account_account_type_alter_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('WAL', 'Mobile Wallet'), ('CHK', 'Checking'), ('INV', 'Investment'), ('SVG', 'Savings')], default='CHK', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('TRN', 'Transfer'), ('INC', 'Income'), ('EXP', 'Expense')], default='EXP', max_length=3),
        ),
    ]
