# Generated by Django 5.1.3 on 2025-02-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_api', '0021_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('INV', 'Investment'), ('SVG', 'Savings'), ('CHK', 'Checking'), ('WAL', 'Mobile Wallet')], default='CHK', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('INC', 'Income'), ('EXP', 'Expense'), ('TRN', 'Transfer')], default='EXP', max_length=3),
        ),
    ]
