# Generated by Django 5.0.7 on 2025-02-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management_api', '0024_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('SVG', 'Savings'), ('WAL', 'Mobile Wallet'), ('INV', 'Investment'), ('CHK', 'Checking')], default='CHK', max_length=3),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('EXP', 'Expense'), ('INC', 'Income'), ('TRN', 'Transfer')], default='EXP', max_length=3),
        ),
    ]
